### ISSUE TITLE
USER STORY <Error Pages>

### ISSUE THREAD

**Issue by rinalds98** [rinalds98/mindful-gents#10]
### Story

As a **user**, I can **navigate the website** so that I can **go back to the homepage incase of an error/page not found**.

### Acceptance Criteria

- In the event of an error 404 a user can return back to the homepage.
- Error 404 page customized to the website theme.

### Tasks

- [ ] Set up a html template for Error 404.
- [ ] Style html template to website theme.
- [ ] Configure website to use custom html template.
