### ISSUE TITLE
USER STORY <Homepage Frontend>

### ISSUE THREAD

**Issue by rinalds98** [rinalds98/mindful-gents#11]
### Story

As a **user**, I can **visit the homepage** so that I can **understand what the website is about**.

### Acceptance Criteria

- A simple minimalistic layout for the front end.
- Passes accessibility in lighthouse. 
- Basic styling to resemble wireframe

### Tasks

- [x] Add html structure to index.html
- [x] Add basic styling to index.html 
- [x] Add Photos / Icons / Media
