### ISSUE TITLE
USER STORY <Crisis Page>

### ISSUE THREAD

**Issue by rinalds98** [rinalds98/mindful-gents#12]
### Story

As a **user**, I can **access the crisis page** so that I can **get quick information on who to contact**.

### Acceptance Criteria

- Simple layout with hotline phone numbers for specific reasons.
- Map of locations that can assist the user where they can go / reach out.

### Tasks

- [x] Add html structure to crisis page.
- [x] Style crisis page.
- [x] Add Map API
- [ ] Add multiple locations with information for the user they they might find useful.
