### ISSUE TITLE
USER STORY <Quiz>

### ISSUE THREAD

**Issue by rinalds98** [rinalds98/mindful-gents#14]
### Story

As a **user**, I can **do a quiz** so that I can **learn more about men's health**.

### Acceptance Criteria

- Have an engaging quiz where the questions are randomized.
- It should have multiple choice Answers / Options.
- The user receives the results of the quiz that they partook in.

### Tasks

- [ ] Create an algorithm that shows different questions each time.
- [ ] Create Html structure and style the page.
- [ ] Create a scoring system that shows the user their result.
