### ISSUE TITLE
USER STORY <Navigation Menu & Footer>

### ISSUE THREAD

**Issue by rinalds98** [rinalds98/mindful-gents#15]
### Story

As a **user**, I can **navigate the website** so that I can **access certain areas of the website**.

### Acceptance Criteria

- Clear navigation links and footer design
- Responsive design
- Quick access links in the footer
- User status is reflected with - (Log in / Log out / Register -- Welcome 'User')

### Tasks

- [x] Implement bootstrap navigation bar.
- [x] Adjust color theme to compliment website.
- [x] Add Logo / Website name to Navigation bar.
- [ ] Add template language that recognizes user status ie. (Log in / Log out / Register -- Welcome 'User')
