### ISSUE TITLE
USER STORY <Style Log in / Log out / Sign Up / Register Pages>

### ISSUE THREAD

**Issue by rinalds98** [rinalds98/mindful-gents#24]
### Story

As a **user**, I can **access and navigate easily log in / Log out / Sign Up / Register Pages ** so that I can **do certain actions**.

### Acceptance Criteria

- Styled and user friendly design similar to the website theme
- Confirm everything is configured properly

### Tasks

- [x] Add styling to pages.
- [x] Restructure html with correct wording and layout.
- [x] Test to see if pressing submit / sign up / log in does the correct action
