### ISSUE TITLE
USER STORY <CSS styling for information Hub>

### ISSUE THREAD

**Issue by rinalds98** [rinalds98/mindful-gents#42]
### Story

As a **user**, I can **view the page** so that I can **easily navigate and understand the information**.

### Acceptance Criteria

- Clean and minimalistic look
- matches website theme
- mobile responsive

### Tasks

- [ ] Add css styling to page.
- [ ] add bootstrap for mobile responsiveness 
- [ ] Use colors from previous pages to create similarity with website overall theme
