### ISSUE TITLE
USER STORY <Wireframes & Color Theme>

### ISSUE THREAD

**Issue by rinalds98** [rinalds98/mindful-gents#5]
### Story

As a **developer**, I can **use wireframes** so that I can **visualize what the website will look like**.

### Acceptance Criteria

- Clear and intuitive navigation elements leading to chat functionality, crisis response and information hub must be part of the wireframe.
- The chat page wireframe should feature a user-friendly interface for initiating conversations with mental health professionals or volunteers.
- The color theme of the website should evoke calmness and empathy.

### Tasks

- [x] Home Page Wireframe
- [x] Chat page Wireframe
- [x] Crisis / helpful info Wireframe
- [x] Color theme of the website - taken from slack chat (#3E403F - Hat grey #4595AB - Dark turquoise #2FCCCB - Light turquoise)
