### ISSUE TITLE
USER STORY <Testing>

### ISSUE THREAD

**Issue by rinalds98** [rinalds98/mindful-gents#53]
### Story

As a **developer**, I can **test the website** so that I can **access all parts of the website**.

### Acceptance Criteria

- Good lighthouse scores
- HTML Validator and accessibility to pass
- All buttons work as intended, All links & error pages
- Debug set to False

### Tasks

- [ ] Run lighthouse and adjust areas where lighthouse score is low
- [ ] HTML validator for any errors
- [ ] Test every link / button / error page
