### ISSUE TITLE
USER STORY <Chat App testing and styling>

### ISSUE THREAD

**Issue by rinalds98** [rinalds98/mindful-gents#54]
### Story

As a **user**, I can **access chat** so that I can **talk to someone**.

### Acceptance Criteria

- I can access the chat functionality.
- It has been styled to the website theme.
- chat works as intended

### Tasks

- [ ] Link chat to the navigation bar and buttons
- [ ] Add styling to chatroom section.
- [ ] Test chat works as intended without errors.
