### ISSUE TITLE
USER STORY <Account Registration>

### ISSUE THREAD

**Issue by rinalds98** [rinalds98/mindful-gents#8]
### Story

As a **user**, I can **register** so that I can **chat with a professional / volunteer**.

### Acceptance Criteria

- Users should be able to access the registration page from the homepage or a dedicated registration link.
- Users should be able to login / logout
- Users must enter a valid email address or username and a corresponding password to log in.

### Tasks

- [x] Add AllAuth authentication to django. 
- [x] Implement Allauth templates.
- [ ] Modify Styling to match website layout.
- [ ] Add log in / log out / register buttons corresponding to the users status on the website.
