### ISSUE TITLE
USER STORY <Initial Project Setup>

### ISSUE THREAD

**Issue by rinalds98** [rinalds98/mindful-gents#9]
### Story

As a **developer**, I can **set up project** so that I can **start working on the project**.

### Tasks

- [x] Set up Django.
- [x] Configure database.
- [x] Configure Heroku and connect database + GitHub repository.
- [x] Configure file structure and wire up static files and templates.
- [x] Configure Bootstrap and font awesome.
